llvm/wg-hlsl

proposals/0001-availability-diagnostics.md
proposals/0002-root-signature-in-clang.md
proposals/0003-packoffset.md
proposals/0004-register-types-and-diagnostics.md
proposals/NNNN-root-signature-in-clang.md

This change adds copies of the infrastructure proposals from https://github.com/microsoft/hlsl-specs that are describing clang/llvm implementation details.

Copy clang proposals from hlsl-specs

---

proposals/0005-inproc-outofproc-compiler-api-support.md

This commit updates the proposal to be in an 'Accepted' state.  A team meeting happened where we all agreed on this approach.

[0005] Mark out of process compiler api proposal as Accepted

---

tools/hlslpm/github.py
tools/hlslpm/gql/get_issue_text.gql
tools/hlslpm/gql/project_item_summary.gql
tools/hlslpm/issue.py
tools/hlslpm/testIssues.py

Previously, this would blindly accept something like `### Foo (??)` as a section heading referring to an issue with reference `??`.  Various things fell over after this, so this change instead only accepts things that look like github-style issues references.
Also included in this change is the infrastructure added to help track down this issue - namely, grabbing more information about each issue and displaying information about that when something goes wrong.

tools/hlslpm: always get issue titles, and don't accept things that aren't issue references in section titles

---

proposals/0006-DXIL-Function-Scalarization.md
proposals/NNNN-DXIL-Scalarization.md

This covers the motivations, background of how Scalarization is working in DXC
and the approach to tasking we should take.
This is also and updated proposal to what was decided in team meeting
It does not cover Data scalarization.

A proposal for DXIL Function Scalarization

---

proposals/0004-register-types-and-diagnostics.md

The `space` parameter will also be validated in `DiagnoseHLSLRegisterAttribute`, and is worth mentioning in the spec.

Add responsibility of space parameter validation to DiagnoseHLSLRegisterAttribute

---

proposals/0008-c-interface-compiler-library.md

This commit adds more information about what the compiler apis look like with example code showing usage.

Add details for the complier api entrypoints and calling patterns to proposal document

---

tools/hlslpm/github.py
tools/hlslpm/gql/get_issues_tracked.gql
tools/hlslpm/gql/get_project_field_id.gql
tools/hlslpm/gql/project_item_summary.gql
tools/hlslpm/gql/set_issue_project_milestone.gql
tools/hlslpm/hlslpm.py
tools/hlslpm/issue.py
tools/hlslpm/updateMilestoneField.py

The ProjectMilestone field allows us to generate [project boards](https://github.com/orgs/llvm/projects/4/views/20) that slice on project milestone.  
This works by ensuring that all issues tracked by a `category:Project Milestone` issue have the same value for the `ProjectMilestone` field.
While doing this is also detects and warns about issues that are tracked by multiple project milestone issues.

[hlslpm] Add command to update ProjectMilestone fields

---

proposals/0002-root-signature-in-clang.md

This commit adds a metadata schema to the root signature.
This schema is used to describe the root signature in llvm IR.

Add metadata schema to root signature

---

proposals/0011-resource-element-type-validation.md

The spec didn't properly reflect that typed buffers should never allow struct element types. This PR adds extra clarification and removes many of the struct test cases. Someone reading the spec should not be able to determine that structs are allowed as typed resource element types.

[0011] Remove struct test cases, clarify structs aren't allowed

---

proposals/0011-resource-element-type-validation.md

Improving whitespace to show separation between typed and raw buffer resources.

[0011] Improve whitespace

---

proposals/0002-root-signature-in-clang.md

Move the example metadata to the main proposal section.
Update the layout of the schema so that it is ordered more from top-to-bottom and reformat to be easier to read.
Also fixed the metadata example to match the schema.

[0002] Root signatures: Fix example and reformat metadata schema

---

proposals/0013-initializer-lists.md
proposals/xxxx-initializer-lists.md

This PR adds a proposal for HLSL initializer list support to align Clang with DXC's behavior while providing a path forward to a better language implementation in the future.

HLSL Initializer List Support

---

proposals/0002-root-signature-in-clang.md

This PR is adding the versioning information to Root Signature specs. It includes:
- adding a new attribute to clang driver to specify root signature versions.
- updating metadata representation to hold root signature versions.
Closes: https://github.com/llvm/wg-hlsl/issues/113

[0002] RootSignatures - Versioning proposal

---

proposals/0002-root-signature-in-clang.md

- adds default value information to the Root Signature specification
Resolves #172

[0002] RootSignatures - Add default values to proposal

---

proposals/0017-inline-spirv-and-decorated-types.md
proposals/nnnn-inline-spirv-and-decorated-types.md

This adds target extension types to represent `SpirvType` from [HLSL 0011, Inline SPIR-V](https://github.com/microsoft/hlsl-specs/blob/main/proposals/0011-inline-spirv.md).

[NNNN] Target Extension Types for Inline SPIR-V and Decorated Types

---

proposals/0018-spirv-resource-representation.md
proposals/XXXX-spirv-resource-representation.md

Adds a proposal for how HLSL resources will be represented in llvm-ir
when targeting SPIR-V.

[0018] SPIRV resource representation

---

proposals/0002-root-signature-in-clang.md

- it appears the `offset` was mistakenly dropped as discarding this information no longer allows the user to provide a manual offset from the start of the descriptors heap and allow for register aliasing
- additionally, we do a small fix-up to update the flag values to be their correct default as we adjust the parameter values
Resolves https://github.com/llvm/wg-hlsl/issues/190

[0002] RootSignatures - Add missing Descriptor Ranges `offset`

---

proposals/0023-typed-buffer-counters.md
proposals/NNNN-typed-buffer-counters.md

This is a proposal to create a separte handle for the
counter resource in RWStructureBuffer and other that have associated
counters.

[NNNN] Proposal for separate counter resource handle

---

docs/issue_tracking.md

Some issues are blocked on design review.  This value can be used to identify them.

Add "Review" value for the "blocked" field

---

proposals/0024-implicit-resource-binding.md

Add one more example showing binding of resource arrays in user-defined structs.
Add a note to re-evaluate whether to bind resource arrays in structs individually or as a continuous descriptor range later on when we start working on the resources in structs design (llvm/wg-hlsl##212).

Resource binding: add another example and notes about resources in structs

---

proposals/0026-symbol-visibility.md
proposals/NNNN-symbol-visibility.md

Section 3.6 of the
[HLSL specification](https://microsoft.github.io/hlsl-specs/specs/hlsl.pdf)
defined the possible linkages for names. This proposal updates how these
linkages are represented in LLVM IR. The current implementation presents
challenges for the SPIR-V backend due to inconsistencies with OpenCL. In HLSL, a
name can have external linkage and program linkage, among others. If a name has
external linkage, it is visible outside the translation unit, but not outside a
linked program. A name with program linkage is visible outside a partially linked program.
We propose that names with program linkage in HLSL should have external linkage 
and default visibility in LLVM IR, while names with external linkage in HLSL should have
external linkage and hidden visibility in LLVM IR. They …

[0026] Add proposal for symbol visibility.

---

proposals/0027-vk-const-id.md
proposals/NNNN-vk-const-id.md

Design for the Clang implmentation of`vk::constant_id`.

[NNNN] Implementation for `vk::constant_id`
